SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, 
        ((SELECT MAX(B.SIZE_OF_COLONY) 
          FROM ECOLI_DATA B 
          WHERE LEFT(A.DIFFERENTIATION_DATE, 4) = LEFT(B.DIFFERENTIATION_DATE, 4))
         - A.SIZE_OF_COLONY) YEAR_DEV,
        A.ID
FROM ECOLI_DATA A
ORDER BY YEAR, YEAR_DEV;