SELECT I.ID, N.FISH_NAME, S.L AS LENGTH
FROM FISH_INFO I JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
JOIN (SELECT FISH_TYPE, MAX(LENGTH) L
    FROM FISH_INFO
    GROUP BY FISH_TYPE) S
ON N.FISH_TYPE = S.FISH_TYPE
WHERE I.LENGTH = S.L
ORDER BY I.ID;